name: subsquare
favicon: null
layout_spectrum: 0.5400194432586432
typography_spectrum: 0.8453816848341376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5496375367511064
  lightness: 0.7497044117189944
  saturation: 0.32677650451660156
  rhythmicContrast: 0.22184722032397985
purpose: []
